spark.master spark://152Server:7077
spark.local.dir  /home/hejiahao/spark-3.3.0-bin-hadoop3/tmp
spark.sql.warehouse.dir  file:/home/hejiahao/spark-warehouse
spark.driver.memory  10g
spark.executor.instances  6
spark.cores.max  36
spark.executor.cores  6
spark.executor.memory  10g
spark.hadoop.fs.defaultFS        file:///
spark.jars /home/hejiahao/Calibra/jar/runtimecost_2.12-0.1.0-SNAPSHOT.jar
spark.sql.calibra.enabled   true
spark.sql.cbo.calibra.enabled   false
spark.sql.physical.calibra.enabled   true
spark.sql.cbo.enabled  true
spark.sql.cbo.joinReorder.dp.threshold  18
spark.sql.cbo.joinReorder.enabled true
spark.sql.statistics.histogram.enabled  true
spark.sql.cbo.planStats.enabled true
spark.sql.optimizer.runtime.bloomFilter.enabled false
spark.sql.queryExecutionListeners cn.edu.ruc.QueryRegisterListener
spark.sql.extensions cn.edu.ruc.LogicalPlanSenderInjector
spark.eventLog.enabled           true
spark.eventLog.dir               file:////home/hejiahao/spark-3.5.4-bin-hadoop3/logs
