spark.master spark://152Server:7077
spark.local.dir  /home/hejiahao/spark-3.3.0-bin-hadoop3/tmp
spark.sql.warehouse.dir  file:/home/hejiahao/spark-warehouse
spark.driver.memory  10g
spark.executor.instances  6
spark.cores.max  36
spark.executor.cores  6
spark.executor.memory  10g
spark.hadoop.fs.defaultFS        file:///
spark.jars /home/hejiahao/RuntimeCost/jar/RuntimeCost-assembly-0.1.0-SNAPSHOT.jar
spark.sql.adaptive.customCostEvaluatorClass cn.edu.ruc.RuntimeCostEvaluator
spark.eventLog.enabled           true
spark.eventLog.dir               file:////home/hejiahao/spark-3.5.4-bin-hadoop3/logs
